### ISSUE TITLE
Is there a geometry type for a region defined by a linear inequality?

### ISSUE THREAD

**Issue by ramiromagno** [thomasp85/euclid#29]
Hi Thomas,

Thanks for the effort put into `{euclid}`. Great logo by the way!

Now, to the issue: can we represent the region $-x_1 + x_2 \leq -5$? And can we plot it? What about intersections of regions like these? Such functionality would be great to accompany exercises on linear programming.

**Comment by thomasp85** [comment]
There is no support for this type of spec in the CGAL 2D/3D linear kernel which is the basis for euclid. The intent of euclid is to be an extendable system (e.g. currently working on polyclid for polygon and polyline types), so if it exists in CGAL someone can make a package for it

**Comment by ramiromagno** [comment]
Thank you for your answer Thomas!
